#!/bin/sh

cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu_run
else
	cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi

cachebuster=RECACHE

chosen=$(
	(
		echo $cachebuster
		cat $cache
	) | dmenu "$@"
)

if test "$chosen" = $cachebuster
then
	dmenu_run
else
	echo "$chosen" | sh
fi
